name: depresence_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^ 1.1.0
  provider: ^6.0.5
  url_launcher: ^6.2.6
  camera: ^0.10.5+9
  intl: ^0.19.0
  flutter_svg: 2.0.10+1
  cupertino_icons: ^1.0.8
  speech_to_text: ^6.6.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/image/


  fonts:
    - family: Beiruti
      fonts:
        - asset: assets/fonts/Beiruti-Regular.ttf

    - family: JustAnotherHand
      fonts:
        - asset: assets/fonts/JustAnotherHand-Regular.ttf

    - family: TraditionalArabic
      fonts:
        - asset: "assets/fonts/Traditional Arabic Regular.ttf"
